from typing import Any, Optional, Sequence, TypeVar, overload

from .ope_data import OPEData
from .operators import NormalOrderedOperator, Operator
from .registry import OPEDefiner

OperatorT = TypeVar("OperatorT", bound=Operator)

class OPEComputer(OPEDefiner):
    def __call__(self, left: Any, right: Any) -> OPEData: ...
    @staticmethod
    def make(data: Any) -> OPEData: ...

OPE: OPEComputer

def MakeOPE(data: Any) -> OPEData: ...
@overload
def NO() -> Any: ...
@overload
def NO(operators: Sequence[Any], /) -> Any: ...
@overload
def NO(operator: OperatorT, /) -> OperatorT: ...
@overload
def NO(left: Operator, right: Operator, /) -> NormalOrderedOperator: ...
@overload
def NO(left: Any, right: Any, /) -> Any: ...
@overload
def NO(operator1: Any, operator2: Any, operator3: Any, /, *operators: Any) -> Any: ...
@overload
def NO_product() -> Any: ...
@overload
def NO_product(operator: OperatorT, /) -> OperatorT: ...
@overload
def NO_product(left: Operator, right: Operator, /) -> NormalOrderedOperator: ...
@overload
def NO_product(
    operator1: Any, operator2: Any, operator3: Any, /, *operators: Any
) -> Any: ...
@overload
def normal_product() -> Any: ...
@overload
def normal_product(operator: OperatorT, /) -> OperatorT: ...
@overload
def normal_product(left: Operator, right: Operator, /) -> NormalOrderedOperator: ...
@overload
def normal_product(
    operator1: Any, operator2: Any, operator3: Any, /, *operators: Any
) -> Any: ...
def bracket(
    left: Any,
    right: Any,
    n: Optional[int] = None,
    anticommutator: Optional[bool] = None,
) -> Any: ...
