from contextlib import AbstractContextManager

def get_compute_backend() -> str: ...
def set_compute_backend(name: str) -> None: ...
def compute_backend(name: str) -> AbstractContextManager[None]: ...
