from typing import Any, Iterable

import sympy as sp

class AlgebraElement:
    algebra: FiniteDimensionalAlgebra
    coordinates: tuple[sp.Expr, ...]
    def as_expr(self) -> sp.Expr: ...
    def is_zero(self) -> bool: ...
    def equals(self, other: Any) -> bool: ...
    def is_scalar_multiple_of(self, other: Any) -> tuple[bool, sp.Expr | None]: ...
    def __add__(self, other: Any) -> AlgebraElement: ...
    def __sub__(self, other: Any) -> AlgebraElement: ...
    def __rmul__(self, scalar: Any) -> AlgebraElement: ...
    def __mul__(self, other: Any) -> AlgebraElement: ...

class MultiplicationTableEntry:
    left: Any
    right: Any
    product: AlgebraElement

class OneDimensionalRepresentation:
    values: dict[Any, sp.Expr]
    def evaluate(self, element: AlgebraElement) -> sp.Expr: ...

class IrreducibleRepresentationClassification:
    dimension: int | None
    irreducible_representations: list[Any]
    method: str
    notes: str

class AlgebraValidationIssue:
    kind: str
    message: str
    left: Any | None
    middle: Any | None
    right: Any | None
    expected: AlgebraElement | None
    actual: AlgebraElement | None

class AssociativityValidationResult:
    is_associative: bool
    issues: list[AlgebraValidationIssue]

class IdentityValidationResult:
    is_identity_valid: bool
    issues: list[AlgebraValidationIssue]

class FiniteDimensionalAlgebra:
    basis_names: tuple[Any, ...]
    index: dict[Any, int]
    identity: Any | None
    structure_constants: dict[tuple[Any, Any], tuple[sp.Expr, ...]]
    def __init__(
        self,
        basis_names: Iterable[Any],
        structure_constants: dict[tuple[Any, Any], dict[Any, Any]],
        identity: Any | None = None,
    ) -> None: ...
    @property
    def dimension(self) -> int: ...
    def basis_element(self, name: Any) -> AlgebraElement: ...
    def basis(self) -> list[AlgebraElement]: ...
    def element(self, coordinates: Iterable[Any]) -> AlgebraElement: ...
    def coerce_element(self, value: Any) -> AlgebraElement: ...
    def multiply(self, left: Any, right: Any) -> AlgebraElement: ...
    def multiplication_table(self) -> list[MultiplicationTableEntry]: ...
    def multiplication_tensor(self) -> sp.MutableDenseNDimArray: ...
    def left_multiplication_operator(self, basis_name: Any) -> sp.Matrix: ...
    def right_multiplication_operator(self, basis_name: Any) -> sp.Matrix: ...
    def left_regular_matrix(self, element: Any) -> sp.Matrix: ...
    def right_regular_matrix(self, element: Any) -> sp.Matrix: ...
    def validate_associativity(self) -> AssociativityValidationResult: ...
    def validate_identity(self) -> IdentityValidationResult: ...
    def solve_one_dimensional_representations(
        self, symbol_map: dict[Any, sp.Symbol] | None = None
    ) -> list[OneDimensionalRepresentation]: ...
    def classify_irreducible_representations(
        self,
    ) -> IrreducibleRepresentationClassification: ...

def build_finite_dimensional_algebra(
    basis_names: Iterable[Any],
    structure_constants: dict[tuple[Any, Any], dict[Any, Any]],
    identity: Any | None = None,
) -> FiniteDimensionalAlgebra: ...
