from typing import Any, Dict, Tuple, Union

import sympy as sp

from .operators import Operator

LocalOperatorType = Union[Operator, sp.Expr]

class LocalOperator: ...
class OperatorSum(sp.Add): ...
class OperatorProduct(sp.Mul): ...

def is_local_operator(expr: Any) -> bool: ...
def assert_no_illegal_operator_mul(expr: Any, context: str) -> None: ...
def extract_scalar_operator(
    expr: sp.Expr,
) -> Tuple[sp.Expr, Union[Operator, sp.Expr]]: ...
def get_operator_parity(expr: LocalOperatorType) -> int: ...
def simplify_with_sympy(expr: LocalOperatorType) -> LocalOperatorType: ...
def collect_operator_terms(expr: LocalOperatorType) -> Dict[Any, Any]: ...
