from typing import Any, Callable, Dict, List, Optional

class OPEData:
    def __init__(self, poles: Optional[Dict[int, Any]] = None) -> None: ...
    @classmethod
    def from_list(cls, pole_list: List[Any]) -> "OPEData": ...
    @property
    def poles(self) -> Dict[int, Any]: ...
    @property
    def max_pole(self) -> int: ...
    def pole(self, n: int) -> Any: ...
    def set_pole(self, n: int, coeff: Any) -> None: ...
    def is_zero(self) -> bool: ...
    def __add__(self, other: "OPEData") -> "OPEData": ...
    def __radd__(self, other: Any) -> "OPEData": ...
    def __mul__(self, scalar: Any) -> "OPEData": ...
    def __rmul__(self, scalar: Any) -> "OPEData": ...
    def __neg__(self) -> "OPEData": ...
    def __sub__(self, other: "OPEData") -> "OPEData": ...
    def __eq__(self, other: Any) -> bool: ...
    def simplify(
        self,
        simplify_func: Optional[Callable[..., Any]] = None,
        expand_derivatives: bool = True,
    ) -> "OPEData": ...
