from typing import Any, Optional, Tuple, overload

import sympy as sp
from sympy.core.symbol import Symbol

class Operator(Symbol):
    @property
    def parity(self) -> int: ...
    def __iter__(self) -> Any: ...
    def realize(self) -> Any: ...
    def simplifyNO(
        self, expand_derivatives: bool = True, preserve_nested_structure: bool = False
    ) -> Any: ...

class BasisOperator(Operator):
    @overload
    def __new__(
        cls,
        name: str,
        conformal_weight: Any,
        indexed: bool = False,
        *,
        fermionic: Optional[bool] = None,
        indices: Optional[Tuple[Any, ...]] = None,
        base_name: Optional[str] = None,
        latex: Optional[str] = None,
        **assumptions: Any,
    ) -> "BasisOperator": ...
    @overload
    def __new__(
        cls,
        name: str,
        fermionic: Optional[bool] = None,
        indexed: bool = False,
        conformal_weight: Optional[float] = None,
        indices: Optional[Tuple[Any, ...]] = None,
        base_name: Optional[str] = None,
        latex: Optional[str] = None,
        **assumptions: Any,
    ) -> "BasisOperator": ...
    @property
    def is_bosonic(self) -> bool: ...
    @property
    def is_fermionic(self) -> bool: ...
    @property
    def parity(self) -> int: ...
    @property
    def base_name(self) -> str: ...
    @property
    def indices(self) -> Tuple[Any, ...]: ...
    @property
    def conformal_weight(self) -> Optional[float]: ...
    @property
    def latex(self) -> Optional[str]: ...
    def set_latex(self, latex: str) -> "BasisOperator": ...

class DerivativeOperator(Operator):
    @property
    def base(self) -> Operator: ...
    @property
    def order(self) -> int: ...
    @property
    def parity(self) -> int: ...
    @property
    def conformal_weight(self) -> Optional[float]: ...

class NormalOrderedOperator(Operator):
    @property
    def left(self) -> Operator: ...
    @property
    def right(self) -> Operator: ...
    @property
    def factors(self) -> Tuple[Operator, Operator]: ...
    @property
    def parity(self) -> int: ...
    @property
    def conformal_weight(self) -> Optional[float]: ...
    def simplifyNO(
        self, expand_derivatives: bool = True, preserve_nested_structure: bool = False
    ) -> Any: ...

@overload
def d(operator: DerivativeOperator, order: int = 1) -> DerivativeOperator: ...
@overload
def d(operator: Operator, order: int = 1) -> DerivativeOperator: ...
@overload
def d(operator: sp.Expr, order: int = 1) -> sp.Expr: ...
def d(operator: Any, order: int = 1) -> Any: ...
@overload
def dn(order: int, operator: DerivativeOperator) -> DerivativeOperator: ...
@overload
def dn(order: int, operator: Operator) -> DerivativeOperator: ...
@overload
def dn(order: int, operator: sp.Expr) -> sp.Expr: ...
def dn(order: int, operator: Any) -> Any: ...
