from typing import Any, Dict, Iterable, List, Optional

import sympy as sp

from .operators import BasisOperator, Operator

class RealizedGenerator(BasisOperator):
    @property
    def realization(self) -> Any: ...

def make_realized(expressions: Any, **assumptions: Any) -> list[RealizedGenerator]: ...
def realize(expr: Any) -> Any: ...
def realize_and_simplify(expr: Any) -> Any: ...
def clear_realize_cache() -> None: ...
def realized_coordinates(
    expr: Any, free_field_basis: "LocalOperatorBasis", weight: Any = None
) -> sp.Matrix: ...
def independent_under_realization(
    expressions: Iterable[Any],
    free_field_basis: "LocalOperatorBasis",
    weight: Any = None,
) -> list[Any]: ...
def list_independent_ops(
    expressions: Iterable[Any],
    basis: "LocalOperatorBasis",
    weight: Any = None,
) -> list[Any]: ...
def list_zero_relations(
    expressions: Iterable[Any],
    basis: "LocalOperatorBasis",
    weight: Any = None,
) -> list[dict[str, Any]]: ...

class LocalOperatorCanonicalizer:
    def __init__(self, generators: Iterable[Operator]) -> None: ...
    def canonicalize(self, expr: Any) -> Any: ...

class SparseLinearContext:
    def __init__(self) -> None: ...

class LocalOperatorBasis:
    generators: tuple[Operator, ...]
    max_weight: Optional[sp.Expr]
    def __init__(
        self, generators: Iterable[Operator], max_weight: Any = None
    ) -> None: ...
    def canonicalize(self, expr: Any) -> Any: ...
    def enumerate_candidates(self, weight: Any) -> list[Any]: ...
    def list(self, weight: Any) -> list[Any]: ...
    def coordinates(self, expr: Any, weight: Any = None) -> sp.Matrix: ...
    def realized_coordinates(
        self, expr: Any, free_field_basis: "LocalOperatorBasis", weight: Any = None
    ) -> sp.Matrix: ...
    def independent_under_realization(
        self,
        expressions: Iterable[Any],
        free_field_basis: "LocalOperatorBasis",
        weight: Any = None,
    ) -> list[Any]: ...

class C2Space:
    basis_builder: LocalOperatorBasis
    def __init__(self, basis_builder: LocalOperatorBasis) -> None: ...
    def generators(self, weight: Any) -> List[Any]: ...
    def basis(self, weight: Any) -> List[Any]: ...
    def contains(self, expr: Any, weight: Any = None) -> bool: ...

class C2NullSearcher:
    basis_builder: LocalOperatorBasis
    def __init__(
        self,
        basis_builder: LocalOperatorBasis,
        stress_tensor: Any = None,
    ) -> None: ...
    def search_from_sources(
        self, target_weight: Any, sources: Iterable[Any], target_expr: Any
    ) -> Optional[Dict[str, Any]]: ...
