from typing import Any, Optional

from .ope_data import OPEData

class OPERegistry:
    def register_operator(self, operator: Any, parity: int) -> None: ...
    def is_registered(self, operator: Any) -> bool: ...
    def get_parity(self, operator: Any) -> Optional[int]: ...
    def get_position(self, operator: Any) -> Optional[int]: ...
    def compare_operators(self, left: Any, right: Any) -> int: ...
    def define_ope(self, left: Any, right: Any, ope_data: OPEData) -> None: ...
    def get_ope(self, left: Any, right: Any) -> Optional[OPEData]: ...
    def has_ope(self, left: Any, right: Any) -> bool: ...
    def clear(self) -> None: ...

ope_registry: OPERegistry

def Bosonic(*operators: Any) -> None: ...
def Fermionic(*operators: Any) -> None: ...
def clear_registry() -> None: ...

class OPEDefiner:
    registry: OPERegistry
    def __init__(self, registry: Optional[OPERegistry] = None) -> None: ...
    def __setitem__(self, key: tuple[Any, Any], value: OPEData) -> None: ...
    def __getitem__(self, key: tuple[Any, Any]) -> Optional[OPEData]: ...
    def __call__(self, left: Any, right: Any) -> OPEData: ...
    @staticmethod
    def make(data: Any) -> OPEData: ...
