from typing import Any, Dict, List, Tuple

from .ope_data import OPEData

def simplify(
    expr: Any, expand_derivatives: bool = True, preserve_nested_structure: bool = False
) -> Any: ...
def collect_normal_ordered_terms(expr: Any) -> Dict[Tuple[Any, ...], Any]: ...
def combine_normal_ordered_terms(expr: Any) -> Any: ...
def flatten_right_no(expr: Any) -> List[Any]: ...
def is_standard_order_no(expr: Any) -> bool: ...
def expand_nested_no(
    expr: Any, max_depth: Any = None, expand_derivatives: bool = False
) -> Any: ...
