from typing import Any

import sympy as sp

from .operator_spaces import LocalOperatorBasis, SparseLinearContext

def zhu_star_product(left: Any, right: Any) -> Any: ...
def zhu_circle_product(left: Any, right: Any) -> Any: ...

class ZhuReductionWitness:
    expr: Any
    remainder: Any
    generators: list[Any]
    coefficients: list[sp.Expr]
    ov_part: Any
    target_weight: sp.Expr | None

class AbstractZhuReducer:
    def quotient_normal_form(self, expr: Any) -> Any: ...
    def is_zero_mod_ov(self, expr: Any) -> bool: ...
    def solve_zhu_witness(self, expr: Any) -> ZhuReductionWitness: ...

class GenericZhuReducer(AbstractZhuReducer):
    canonicalizer: LocalOperatorBasis
    linear_context: SparseLinearContext
    generator_provider: Any
    def __init__(
        self,
        canonicalizer: LocalOperatorBasis,
        linear_context: SparseLinearContext | None = None,
        generator_provider: Any = None,
    ) -> None: ...
    def candidate_generators_for_expr(self, expr: Any) -> list[Any]: ...
    def candidate_generators_for_weight(self, target_weight: Any) -> list[Any]: ...

class ZhuSpace:
    basis_builder: LocalOperatorBasis
    def __init__(self, basis_builder: LocalOperatorBasis) -> None: ...
    def generators(self, weight: Any) -> list[Any]: ...
    def basis(self, weight: Any) -> list[Any]: ...
    def contains(self, expr: Any, weight: Any = None) -> bool: ...
    def quotient_normal_form(self, expr: Any, weight: Any = None) -> Any: ...
    def is_zero_mod_ov(self, expr: Any, weight: Any = None) -> bool: ...
    def solve_zhu_witness(
        self, expr: Any, weight: Any = None
    ) -> ZhuReductionWitness: ...
    def multiply(self, left: Any, right: Any, weight: Any = None) -> Any: ...
